# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGXBrosAlUYH3g2JSEimmSfEqWVFPaGO
"""

array = ["水","金","地","火","木","土","天","海","冥"]

i = 0

while i < 2:
 for arrays in array:
  print(arrays)
 i = i + 1



