# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGXBrosAlUYH3g2JSEimmSfEqWVFPaGO
"""

#def 関数名(引数名):引数を使った一連の処理
def total_price(price, tax):
  total_price = price * (1 + tax)
  return total_price

# 関数の呼び出し
price = 1000  # 商品の金額
tax = 0.10  # 消費税率（10%）
total = total_price(price, tax)
print(f"商品の合計金額は: {total}円")



